---
title: Infraestructuras críticas Sector químico 
authors:
  - name: Catalina ALberto
    affiliation: Ingeniería UnCUYO
    email: catavalberto@gmail.com
  - name: Dalia Orlinski
    affiliation: Ingeniería UnCUYO
    email: daliaorlinski@gmail.com
  - name: Victoria SIlva
    affiliation: Ingeniería UnCUYO
    email: victoriasilva201101@gmail.com
  - name: Andrés Soria
    affiliation: Ingeniería UnCUYO
    email: andressoria1221@gmail.com
  - name: Macarena Vacas
    affiliation: Ingeniería UnCUYO
    email: macarenavacas2014@gmail.com

bibliography: references.bib
biblio-style: unsrt
output: rticles::arxiv_article
---



# Introducción
\label{sec:headings}

En el siguiente informe se desarrollará un breve resumen del tema Infraestructuras críticas, con la información proporcionada en el seminario de “INFRAESTRUCTURAS CRÍTICAS Y DE NUEVA GENERACIÓN” dictado por el profesor Gustavo Masera. En específico se abordará uno de los 16 sectores que CISA considera como Infraestructuras críticas, el Sector químico.


# Infraestructuras críticas
\label{sec:others}

Antes de centrarnos en el desarrollo es necesario definir que es una Infraestructura y que hace que la misma sea crítica.

Infraestructura se refiere al conjunto de instituciones, redes y sistemas que son fundamentales para el funcionamiento de la sociedad. Proporcionan la base para que las actividades económicas y políticas puedan desarrollarse de una manera eficiente.
Las infraestructuras se crean y funcionan en la intersección de distintas áreas profesionales, es importante unir los distintos agentes de la sociedad (Privados, públicos, etc) con el objetivo de mejorar las mismas y así lograr mayor productividad, mejor acceso a los mercados internacionales y una mayor protección de los bienes públicos.

Se pueden clasificar las infraestructuras según sus características o su finalidad, dentro de la primera existe una clasificación llamada “Infraestructuras críticas”. Estas son aquellas que se consideran esenciales para el funcionamiento de una sociedad, tanto así que una perturbación o destrucción afectaría gravemente a la seguridad nacional, la salud pública, la economía o el bienestar de la población.

# Sector químico
El sector químico se posiciona como un gigante dentro de la economía de los EEUU, generando gran impacto en distintos aspectos. Es el sector con  mayor porcentaje de exportación y es una gran fuente de generación de empleo.

Éste se encarga de convertir más de 700.000 materias primas en productos finales para diversos sectores. Existen cuatro componentes principales


- Químicos básicos: La base fundamental para la elaboración de otros productos químicos.

- Productos químicos especiales: Utilizados en industrias específicas como la farmacéutica, la cosmética y la electrónica.

- Químicos agrícolas: Indispensables para la producción agrícola y el cuidado de los cultivos.

- Productos de consumo: Presentes en nuestro día a día, desde artículos de limpieza hasta materiales de construcción.
 
Los productos químicos de consumo, en particular, generan una dependencia crítica de los sectores de infraestructura, lo que hace que la industria química sea un componente esencial de la seguridad nacional y económica.

El sector químico está sujeto a diversos problemas transversales, tales como infraestructura de transporte obsoleta, dependencia con otros sectores, accidentes industriales, entre otros. Estos pueden generar interrupción en las cadenas de suministro, aumento en los gastos de capital, pérdida de información sensible de seguridad y operaciones, y tener otros impactos graves. Reconocerlos e intentar mitigarlos es crucial para un desarrollo eficiente.

A continuación se presenta un breve resumen de los distintos problemas y como afectan a la sociedad

- Infraestructura de transporte obsoleta

El sector químico requiere transporte adecuado para operar de manera efectiva y segura. La antigüedad y el mal estado de carreteras, puentes, calles y puertos crean una mayor vulnerabilidad de las infraestructuras a las interrupciones, lo que puede generar retrasos.

En el 2017 la Sociedad Americana de Ingenieros Civiles realizó un informe que calificó la Infraestructura de transporte de los Estados Unidos con una D+, lo que significa que este sector Unidos presenta importantes deficiencias que afectan negativamente su funcionamiento y seguridad. Para mejorar esta calificación se deberían tomar medidas tales como aumento del gasto en estas infraestructuras, establecer políticas de mantenimiento a largo plazo, aplicación de nuevas tecnologías, entre otras.

- Dependencia en otros sectores

El sector químico utiliza continuamente los recursos de agua y energía. También depende de sectores tales como Comunicaciones, Tecnologías de la Información, Servicios Financieros y Sistemas de Transporte. Cualquier interrupción, falla o destrucción de alguno de estos generaría un impacto negativo en la industria química.
A su vez los productos químicos son esenciales para el desarrollo de otros sectores, incluyendo las industrias alimenticia, agrícola, de la salud, sistemas de agua, entre otros. Es decir que una interrupción en el mismo generaría un gran impacto en la sociedad.

Se destaca la interdependencia de las infraestructuras críticas de una sociedad, el estado debe contar con una capacidad de anticipación y recuperación; con planes de protección y redes de alerta temprana. Así podrá lograr mitigar las fallas en alguna infraestructura que luego podría afectar a las demás.

- Accidentes industriales

Si bien el sector químico opera con un alto nivel de seguridad, los accidentes pueden ocurrir. Datos mes a mes de CSAC indican que los accidentes industriales representan un tercio de los incidentes químicos reportados. Los reportes indican que estos incidentes generalmente involucran almacenamiento, transporte, producción y laboratorios. 

Los accidentes pueden ocurrir ya sea por errores humanos o por procesos defectuosos, se detectó que existen equipos obsoletos y falta de mantenimiento preventivo. 
Es importante que las empresas entiendan el peso que tiene el sector químico en la sociedad y que un error puede generar grandes consecuencias, por esto se deben llevar a cabo mantenimientos periódicos así como inspecciones reglamentarias por el lado del estado con el objetivo de prevenir accidentes irremediables.


# Conclusión

Con la información brindada en el seminario y las lecturas de distintos reportes de CISA, se pudo comprender la importancia de las infraestructuras críticas para un desarrollo eficiente de la sociedad. Es fundamental que los diferentes actores colaboren estrechamente para lograr mejoras en los aspectos sociales, económicos y medioambientales.

Se comprendió la importancia del sector químico para diversos sectores de la sociedad, y cómo distintos problemas podrían afectar a estos sectores. Por lo tanto, es crucial desarrollar planes de contingencia y alerta temprana para mitigar estos riesgos.

# Referencias

[CISA](https://www.cisa.gov/topics/critical-infrastructure-security-and-resilience/critical-infrastructure-sectors/chemical-sector)
